name: Android APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Opataz-AI-APK
          path: bin/*.apk
